# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 823f5c6838ca1527bd3f4a3b988ebb1af914cf33a4fab6883a951794b6aefc64472783e93e49a307b1240e9d7f5606fd7bd072d2594d74f3ac6e818ef07050ec

test:
  secret_key_base: 137dc05c1617763c2f91d390eb7554b2cb0b31e3137bd1f39f8f1636ff4f91f9ca2493e119f81953dce5fb0de8dad1b325899ae8d7af8f4f7acc19a7911e42e2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
